# Generated by Django 5.1.4 on 2024-12-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='video',
            new_name='audio',
        ),
    ]
